import streamlit as st
st.title('첫번째 웹 어플 만들기')
st.write('# 1. Markdown 텍스트 작성하기')
st.write('## 마크다운 H3 : st.write()')
st.write('') 
st.title('제목 : st.title()')
st.header('헤더 : st.header()')
st.subheader('서브헤더 : st.subheader()')
st.text('본문 텍스트 : st.text()') 
st.write('')
st.markdown('# 마크다운 : st.markdown()')
